"""empty message

Revision ID: 07a2f59c5cb9
Revises: 2e8f83a91c47
Create Date: 2020-03-03 18:49:31.985615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a2f59c5cb9'
down_revision = '2e8f83a91c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'answer')
    # ### end Alembic commands ###
