"""empty message

Revision ID: 58020360ad68
Revises: 6a8773a2adad
Create Date: 2020-03-05 15:11:32.910179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58020360ad68'
down_revision = '6a8773a2adad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('first_name', sa.String(), nullable=True))
    op.drop_column('card', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('card', 'first_name')
    # ### end Alembic commands ###
