"""empty message

Revision ID: 6a8773a2adad
Revises: a4e60ec6d233
Create Date: 2020-03-05 15:08:06.832225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8773a2adad'
down_revision = 'a4e60ec6d233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'name')
    # ### end Alembic commands ###
