"""empty message

Revision ID: 8a44b35b5702
Revises: 07a2f59c5cb9
Create Date: 2020-03-04 13:35:42.315578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a44b35b5702'
down_revision = '07a2f59c5cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_table',
    sa.Column('access_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('access_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_token_table')
    # ### end Alembic commands ###
