"""empty message

Revision ID: a4e60ec6d233
Revises: 8a44b35b5702
Create Date: 2020-03-05 09:30:34.720770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e60ec6d233'
down_revision = '8a44b35b5702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('user', sa.Column('dob', sa.String(), nullable=True))
    op.add_column('user', sa.Column('mobile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'designation')
    # ### end Alembic commands ###
